### ISSUE TITLE
Clollidable class for spawning obstacles and powerups

### ISSUE THREAD

**Issue by dk949** [Team-13-RLC/ENG1Project#8]
## Moving all spawning logic into an abstract class which Obstacle and Powerup inherit from
* In order to minimize the amount of refactoring that needs to be done, I propose renaming the class `Obstacle` to `Collidable` and merging all of the functionality into it.
	* This would also mean merging `ObstacleType` and `PowerupType` into a `CollidableType` enum.
* The damage would be dealt in the same way powerup effects take place, I.e. by invoking a functional interface on the boat object.
* This would change the collision detection loop in `Boat` to this:
```java
protected boolean checkCollisions() {
        ArrayList<Collidable> collidables = this.lane.getCollidables();
        int size = collidables.size();
        for (int i = 0; i < size; i++) {
            Collidable collidable = collidables.get(i);
            if (collidable.getHitBox().collidesWith(this.hitbox)) {
                collidable.dispose();
                this.lane.removeCollidable(collidable);
                size--;
//                this.health -= collidable.getDamage() * buff; // Old
                collidable.takeEffect(this); // New
                return true;
            }
        }
        return false;
    }
```

**Comment by Pyrobow** [comment]
Nice, I'm assuming that takeEffect applies whatever effect the obstacle would do.

**Comment by dk949** [comment]
> Nice, I'm assuming that takeEffect applies whatever effect the obstacle would do.

Yes. For powerups it would mean restoring health or increasing spread (or whatever the power up does) and for obstacles it's reducing health.
